APP:
  ENVIRONMENT: DEV
  DEBUG: True

SPOTIFY:
  BEARER_TOKEN:
    URL: https://accounts.spotify.com/api/token
    METHOD: POST
    GRANT_TYPE: client_credentials
    
  API:
    # HOST: api.spotify.com 
    # VERSION: v1
    # PROTOCOL: https
    URL: https://accounts.spotify.com/api/token
    METHOD: POST
    GRANT_TYPE: client_credentials
    CONTENT_TYPE: application/x-www-form-urlencoded

